### ISSUE TITLE
Duplicated native

### ISSUE THREAD

**Issue by Mathu-lmn** [citizenfx/natives#1109]
Hello, this native is twice in the natives documentation with the same name : 
![image](https://github.com/citizenfx/natives/assets/80094438/c4593008-8c76-4ad1-82a9-3e96c81730b3)

**Comment by PsychoShock** [comment]
This is not a issue, look at the raw name. 

- SET_TEXT_DROPSHADOW
- SET_TEXT_DROP_SHADOW

**Comment by Mathu-lmn** [comment]
So how is Lua handling this difference?

**Comment by PsychoShock** [comment]
There's a difference too.
![image](https://github.com/citizenfx/natives/assets/94499608/99eac37a-aa63-4c49-8047-0e7d67471a48)

**Comment by Mathu-lmn** [comment]
Alright, a bit weird to have 2 such similar natives but eh :)
