### ISSUE TITLE
[issue/question] Native information present in core files that is missing from natives documentation. Intended or issue?

### ISSUE THREAD

**Issue by alberttheprince** [citizenfx/natives#1159]
Was looking up information on the native IsFirstPersonAimCamActive and was directed to core files through a Google search:

https://runtime.fivem.net/artifacts/fivem/build_client/master/9282-ecd511b7f05629ff09765cd397ad2e15a69854de/caches/fivereborn/citizen/clr2/lib/mono/4.5/CitizenFX.Core.xml

![image](https://github.com/user-attachments/assets/918c5644-5c8a-442f-a411-0c7ebcff1f6d)

However, Natives documentation lacks this info:

![image](https://github.com/user-attachments/assets/12731c66-1848-437d-9ba8-18a226b672ea)

https://docs.fivem.net/natives/?_0x5E346D934122613F

Is this intended? Just casually scrolling through this, it seems like a lot of this should be in the documentation and isn't. Is it worth making a PR with info manually found in these files, or is this an issue that CFX could solve in a more efficient/automated manner?

**Comment by AvarianKnight** [comment]
This is documentation on the wrapper(s) C# has (see https://github.com/citizenfx/fivem/blob/ecd511b7f05629ff09765cd397ad2e15a69854de/code/client/clrcore/External/Camera.cs#L689-L701)

The only documentation that is shared through the files is the native declarations, looking at the generated NativesFive.cs (which is generated from the native docs) the documentation (or lack thereof) matches.

```cs
/// <summary>
/// IS_FIRST_PERSON_AIM_CAM_ACTIVE
/// </summary>
[System.Security.SecuritySafeCritical]
public static bool IsFirstPersonAimCamActive()
{
return InternalIsFirstPersonAimCamActive();
}
```

Automating this is basically impossible at the moment, unless we have something to generate all wrapper classes, which is very unlikely to happen.

PRs to improve the natives is always welcomed though. 😄

**Comment by alberttheprince** [comment]
> PRs to improve the natives is always welcomed though. 😄

Sure, I don't mind to PR some of the stuff I find as I come across them. Should I close this issue or leave it open? Feel like if some enterprising individual wanted to find a "solution" for this they could.

**Comment by AvarianKnight** [comment]
> Should I close this issue or leave it open?

I'll go ahead and close this.
