### ISSUE TITLE
GET_GAMEPLAY_CAM_ROT not return Vector3

### ISSUE THREAD

**Issue by serkandyck** [citizenfx/natives#148]
i'm try latest artifact this, and this function return -105003971 like one integer

**Comment by PichotM** [comment]
![image](https://user-images.githubusercontent.com/8015411/61395578-0dcc6200-a8c6-11e9-8852-ab7897fffd99.png)
no

try with this resource_manifest_version "05cfa83c-a124-4cfa-a768-c24a5811d8f9"

**Comment by serkandyck** [comment]
> ![image](https://user-images.githubusercontent.com/8015411/61395578-0dcc6200-a8c6-11e9-8852-ab7897fffd99.png)
> no
> 
> try with this resource_manifest_version "05cfa83c-a124-4cfa-a768-c24a5811d8f9"

ahhh yep i'm try this and worked, thank you
