### ISSUE TITLE
modify weapon dmg?

### ISSUE THREAD

**Issue by Jhudri** [citizenfx/natives#201]
N_0x4757f00bc6323cfe(GetHashKey("WEAPON_NIGHTSTICK"), 0.1)

**Comment by nimoalr** [comment]
@Jhudri what is the purpose of this issue actually? 🤔

**Comment by Jhudri** [comment]
Found it in a script that modified/lowerd weapon dmg. Hit points. For instance the nightstick set to 0.1 takes a ton of strikes to anouther player to down them. I havent tried it on guns but i would assume its has the same effect.

**Comment by smallo92** [comment]
You know issues are for you know.. issues. Not for telling us about a native that has already been PR'd. 
https://github.com/citizenfx/natives/pull/195

**Comment by Jhudri** [comment]
Yeah sorry first time and just noticed this native in a pull request frim 6 fays ago. Please close thank you
