### ISSUE TITLE
bug in CREATE_RUNTIME_TEXTURE_FROM_DUI_HANDLE 

### ISSUE THREAD

**Issue by manups4e** [citizenfx/natives#254]
as stated here https://runtime.fivem.net/doc/natives/?_0xB135472B

in c# native is reported to need a string value as second param.. but in API it wants a long value.. forcing everyone to use Function.Call instead calling the Native directly

![image](https://user-images.githubusercontent.com/4005518/74759851-bafec280-5279-11ea-8e48-044f3823d3e4.png)

**Comment by gottfriedleibniz** [comment]
Fixed in https://github.com/citizenfx/fivem/commit/f1238a89b2f617fc5b3828f769985227e73c765b#diff-5b1d44bcd73bcdd01074dc3162a570f7f51f24bf43d1a71d9cdae11bbe4b1d3e . 

This can be closed.
