### ISSUE TITLE
SET_FOLLOW_VEHICLE_CAM_VIEW_MODE

### ISSUE THREAD

**Issue by makfcb** [citizenfx/natives#286]
https://runtime.fivem.net/doc/natives/#_0xAC253D7842768F48 Only works in cars, doesnt work in bikes or motorcycles

**Comment by stannum-cfx** [comment]
Please make a pull request for this instead of an issue.

By the way, if you're going to document it, the native doesn't work with boats, helicopters or planes either 😉
