### ISSUE TITLE
EnableDispatchService native 

### ISSUE THREAD

**Issue by Rasinzz** [citizenfx/natives#312]
Whenever I try to use [this native](https://github.com/citizenfx/natives/blob/master/MISC/EnableDispatchService.md) I doesn't work properly. 

**Artifact Version:** 2430
**F8 Error:** https://i.imgur.com/L3ZuXCp.png

**Comment by Zeemahh** [comment]
Not an issue with the native. Use `fxmanifest.lua` or use a manifest version.

**Comment by Rasinzz** [comment]
Ok, thank you! I'll give it a try.

**Comment by Rasinzz** [comment]
Ok, it worked. I appreciate it!
