### ISSUE TITLE
After SetVehicleModKit(vehicle, 0) is used on a vehicle GetVehicleNumberPlateText(vehicle) returns an empty string on the server.

### ISSUE THREAD

**Issue by enc0ded** [citizenfx/natives#315]
Repro
https://github.com/enc0ded/GetVehicleNumberPlateText_bug_repro

**Comment by renaiku** [comment]
```cpp
bool hasPlate = state.buffer.ReadBit();

for (int i = 0; i < 8; i++)
{
    if (hasPlate)
    {
        int plateChar = state.buffer.Read<int>(7);
        data.plate[i] = plateChar;
    }
    else
    {
        data.plate[i] = ' ';
    }
}
```

Is it possible that your vehicle has no plate ?

**Comment by enc0ded** [comment]
In the repro I set the plate the same way on both vehicles. Only one returns blank serverside. However, GetVehicleNumberPlateText() client side still returns correct plate.

**Comment by Enz0Z** [comment]
Hey! I'm currently having the same issue, using vMenu, simply add a level 2 engine, and *woop*, the plate appears to be ' '. And yes, on the client-side works perfectly.

**Comment by gottfriedleibniz** [comment]
If this is still an issue, please move it to forums so it won't get lost. Thanks.
