### ISSUE TITLE
RegisterCommand removes hashtags from args

### ISSUE THREAD

**Issue by Sampleeeee** [citizenfx/natives#376]
Not sure if this is the right place but issues are disabled on citizenfx/fivem so I thought this would be the best place to post it. Please correct me if I'm wrong

Seems like if an argument contains a hashtag in the args table, it returns nil
```lua
RegisterCommand("test_command", function(source, args, raw)
    print(args[1])
    print(raw)
end)
```

`/test_command #test` 
> nil
> test_command #test 

Thought maybe it would only happen if it starts with a hashtag, that wasn't the case
`/test_command t#test`
> nil
> test_command t#test

**Comment by blattersturm** [comment]
Not the right place at all. You are aware the FORUMS have a section for bug reports, right?
