### ISSUE TITLE
Missing arg in GET_PLAYER_MELEE_WEAPON_DAMAGE_MODIFIER (server)

### ISSUE THREAD

**Issue by manzarek123** [citizenfx/natives#377]
the following native should be taking a playersrc as argument:
https://runtime.fivem.net/doc/natives/?_0x8689A825
Calling it is trowing an error:
![image](https://user-images.githubusercontent.com/5868611/97363377-c42d3e00-18a2-11eb-85c4-ed22f73e29e1.png)

**Comment by Disquse** [comment]
Thanks, this is going to be fixed soon.
https://github.com/citizenfx/fivem/pull/567

**Comment by Vinipux322** [comment]
Thank you for writing about this, i fixed it https://github.com/citizenfx/fivem/pull/567
