### ISSUE TITLE
0x2491A93618B7D838 native

### ISSUE THREAD

**Issue by ElPumpo** [citizenfx/natives#426]
The native is missing from the list. It's used to flip to the selfie camera on `CellCamActivate()`. Possible name: `CellFrontCamActivate()`. It has one boolean argument, when set to `true` it will use the front camera, and when set to `false` it returns to the back camera

**Comment by gottfriedleibniz** [comment]
`0x2491A93618B7D838` is a mapping to the the v323 native `0x015C49A93E3E086E` . The native repository doesn't maintain (or show?) crossmap information, however, https://github.com/citizenfx/fivem/blob/master/code/components/rage-scripting-five/include/CrossMapping_Universal.h can be referenced.

This can be closed.
