### ISSUE TITLE
Citizen.CreateThread is real multi-threading?

### ISSUE THREAD

**Issue by Allexin** [citizenfx/natives#472]
https://docs.fivem.net/docs/scripting-reference/runtimes/lua/functions/Citizen.CreateThread

Is word "thread" in this article mean real thread?
As i understand scheduler code - thread is not real thread and just wrapper around coroutine.
So all coroutines execute one by one without parallelisation.
Am i right?

**Comment by Allexin** [comment]
No official answer?

**Comment by gottfriedleibniz** [comment]
https://www.lua.org/manual/5.4/manual.html
> The type thread represents independent threads of execution and it is used to implement coroutines (see §2.6). Lua threads are not related to operating-system threads. Lua supports coroutines on all systems, even those that do not support threads natively.

**Comment by Allexin** [comment]
Ok. Thanks. I get your point

**Comment by jeboydennis** [comment]
Disconnected by server: Timed out after 60 seconds (2)
TIMEOUT INFO:
Run game frame: -765 -714 -663 -612 -561 -510 -459 -408 -357 -306 -255 -204 -153 -102 -51 -0
Receive data from server: -816 -765 -714 -663 -612 -561 -510 -459 -408 -357 -306 -255 -204 -153 -102 -51
Send data to server: -1275 -1173 -1122 -1071 -1020 -969 -867 -765 -663 -561 -459 -357 -255 -153 -102 -51

Guide to interpreting above data: each number is the amount of milliseconds between now and a 'tick' of this type.
If any are above ~5000, the specified row is likely to be an issue.
