### ISSUE TITLE
VEHICLE/SetTyreTractionLossMultiplier does not exist.

### ISSUE THREAD

**Issue by sfinktah** [citizenfx/natives#490]

**Comment by blattersturm** [comment]
> have you been foolishly copying alexander blade's cross maps? 

If it is so 'foolish', do you have any better alternative that is available to us?

**Comment by sfinktah** [comment]
Unfortunately I am prohibited by a federal court order from assisting in the development of GTA5 cheats, etc.  But I would suggest https://github.com/Maestro-1337/GTA-V-1.54-Crossmap/blob/master/Crossmap.h as a good place to validate your data (or alloc8or's data) from.

**Comment by blattersturm** [comment]
> Unfortunately I am prohibited by a federal court order from assisting in the development of GTA5 cheats, etc. 

It's a shame your account is using a pseudonym, as I bet Take-Two will be pretty happy to know that you're providing help with a GTA V modification by reporting a supposed issue.

**Comment by sfinktah** [comment]
I'm afraid I have no idea what you are referring to.

**Comment by blattersturm** [comment]
Perhaps it should be noted that using a pseudonym means nobody will find out what you're trying to help out.

You can contact me via E2E Matrix chat at @blattersturm:cfx.re if you need to speak about anything OTR.
