### ISSUE TITLE
GetEntityScript

### ISSUE THREAD

**Issue by mixass** [citizenfx/natives#662]
GetEntityScript is not working on server side (return nil all time)

AddEventHandler('entityCreating', function(entity)
    print(GetEntityScript(entity))
end)
result : nil

**Comment by jaymo1011** [comment]
This would belong under [citizenfx/fivem](/citizenfx/fivem) and not the native database but even more importantly, this should be a correctly formatted bug report via [forum post](https://forum.cfx.re/c/general-discussion/bug-reports/28).
