### ISSUE TITLE
--- ns: VEHICLE aliases: ["0x9D44FCCE98450843"] --- ## _SET_VEHICLE_SILENT  ```c // 0x9D44FCCE98450843 0x968E5770 void _SET_VEHICLE_SILENT(Vehicle vehicle, BOOL toggle); ```  ``` If set to TRUE, it seems to suppress door noises and doesn't allow the horn to be continuous.   ```  ## Parameters * **vehicle**:  * **toggle**: 

### ISSUE THREAD

**Issue by GmaGmkyui-493** [citizenfx/natives#920]
---
ns: VEHICLE
aliases: ["0x9D44FCCE98450843"]
---
## _SET_VEHICLE_SILENT

```c
// 0x9D44FCCE98450843 0x968E5770
void _SET_VEHICLE_SILENT(Vehicle vehicle, BOOL toggle);
```

```
If set to TRUE, it seems to suppress door noises and doesn't allow the horn to be continuous.  
```

## Parameters
* **vehicle**: 
* **toggle**:

**Comment by thorium-cfx** [comment]
You've created an issue where a PR would've been the correct choice for additions like these.

Could you also make sure that the "seems" in "it seems to suppress door noises and doesn't allow the horn to be continuous" is a certainty?

Closing this and would like to see this as a PR instead.
