### ISSUE TITLE
How can I get intrinsic matrices and transformation matrices from depth to world corrdinate?

### ISSUE THREAD

**Issue by choiszt** [citizenfx/natives#928]
Thank you for the invaluable contribution to the GTA-V natives toolbox! I'm currently attempting to align point cloud data from RGBD collected in GTA-V. However, I'm struggling to find the appropriate intrinsic matrices. Moreover, I've been unable to locate the extrinsic matrix necessary to accurately transform the depth image to world coordinates. I suspect the depth images might not be in the camera coordinates, which means I can't directly apply the camera parameters for the transformation. Any insights or experience you could share would be greatly appreciated. Thank you in advance!

**Comment by AvarianKnight** [comment]
This doesn't seem to be related to native documentation, you should try the [Cfx.re Discord](https://discord.gg/fivem)
