### ISSUE TITLE
Migrate FiveM Natives into native pepository

### ISSUE THREAD

**Issue by ahcenezdh** [citizenfx/natives#946]
Hey, why are server-side natives in the FiveM repository and not this one? All natives could be centralized here no?

**Comment by hjklwasntavailable** [comment]
AFAIK it's meant to separate vanilla gta v's natives from CFX namespace (custom) natives, so it's not only server-side natives that aren't here, but every 'cfx native'

**Comment by ahcenezdh** [comment]
Oh okay, is there a technical reason to do that? Because when adding natives into the repository, it's possible to add the API set filter, which is only for FiveM natives (apiset: server or apiset: client)

**Comment by 4mmonium** [comment]
As hjklwasntavailable said, it's because those are the custom ones in the FiveM codebase; they are actually declared [here](https://github.com/citizenfx/fivem/tree/master/ext/native-decls) as part of the documentation and in the docs section they should show up under the CFX category.

**Comment by ahcenezdh** [comment]
Okay thanks!
