### ISSUE TITLE
Update N_0x83a169eabcdb10a2

### ISSUE THREAD

**Issue by CritteRo** [citizenfx/natives#989]
This native is referenced as `PED::SET_PED_PHONE_PALETTE_IDX` in nativedb: https://alloc8or.re/gta5/nativedb/?n=0x83A169EABCDB10A2

Would be nice to have the native name changed, and also documented, so future users won't need to dig through old code to find the native.

It has 2 params, first param is the ped ID, second is the ID of the phone palette. The pallets mimic the IDs of CELLPHONE_IFRUIT themes: 
```
0=blue,
1=green,
2=red,
3=orange,
4=gray,
5=purple,
6=pink,
7 or more = dark-gray?
```

Current lua example:
```lua
N_0x83a169eabcdb10a2(PlayerPedId(), 3)
```

Example image of the phone case being changed:
![image](https://github.com/citizenfx/natives/assets/64140178/09c7ce9f-3f44-49f6-809c-3072939b6673)

**Comment by PsychoShock** [comment]
You are free to PR the modification. You can check [this](https://github.com/citizenfx/natives/blob/master/.github/CONTRIBUTING.md) if you never PR a native! If you do something wrong, you'll be told what's the issue and how to fix it :)

Contributions are always welcome in FiveM / RedM.

**Comment by ahcenezdh** [comment]
> This native is referenced as `PED::SET_PED_PHONE_PALETTE_IDX` in nativedb: https://alloc8or.re/gta5/nativedb/?n=0x83A169EABCDB10A2
> 
> Would be nice to have the native name changed, and also documented, so future users won't need to dig through old code to find the native.
> 
> It has 2 params, first param is the ped ID, second is the ID of the phone palette. The pallets mimic the IDs of CELLPHONE_IFRUIT themes:
> 
> ```
> 0=blue,
> 1=green,
> 2=red,
> 3=orange,
> 4=gray,
> 5=purple,
> 6=pink,
> 7 or more = dark-gray?
> ```
> 
> Current lua example:
> 
> ```lua
> N_0x83a169eabcdb10a2(PlayerPedId(), 3)
> ```
> 
> Example image of the phone case being changed: ![image](https://private-user-images.githubusercontent.com/64140178/304527242-09c7ce9f-3f44-49f6-809c-3072939b6673.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxOTIzNTksIm5iZiI6MTcwODE5MjA1OSwicGF0aCI6Ii82NDE0MDE3OC8zMDQ1MjcyNDItMDljN2NlOWYtM2Y0NC00OWY2LTgwOWMtMzA3MjkzOWI2NjczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjE3VDE3NDczOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkyODdjMzc0ZWRjZmJlNmYyZmE5ZDc3OTEyYTFlNmJkM2RlNDY0YWE5NmMzYmI4MTZmNmU1MzBjMzViOTZlNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Y4nistD-dz0dEwuAauBnYDDqP2m75F956tugk_RCQBc)

Should be good, just have to wait until my PR is merged

**Comment by PsychoShock** [comment]
This can be close @4mmonium since it was push on https://github.com/citizenfx/natives/pull/993
